before:
  hooks:
    - script/generate
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: .
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
