#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

usage_pattern="<!--- start usage output --->*<!--- end usage output --->"

usage_sub="$(cat <<EOF
<!--- start usage output --->
\`\`\`
$(COLUMNS=100 script/semver-select --help)
\`\`\`
<!--- end usage output --->
EOF
)"

readme="$(cat README.md)"
echo "${readme//$usage_pattern/$usage_sub}" > README.md
